development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sk_web_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sk_web_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sk_web_production
